### ISSUE TITLE
General Store

### ISSUE THREAD

**Issue by FPS-86** [LeonZ2019/Lucky-s-Wasteland-Server#1]
Hello. Again I am writing to you with a problem that I encountered yesterday. In the General Store there is a problem with buying things, that is, when you try to buy something, things are not bought. There are no such problems at other stores like buying weapons and equipment.

There are no errors in the logs

**Comment by LeonZ2019** [comment]
Here the commit https://github.com/LeonZ2019/Lucky-s-Wasteland-Server/commit/30b188b41eccf663bb23145d206a919b2f2c7361
